#ifndef KEY_CFG_H_
#define KEY_CFG_H_
//////////////////////////////////////////////////////////////////////////////////////
#ifdef __cplusplus
extern "C" {
	#endif
	//////////////////////////////////////////////////////////////////////////////////////
	#include "complier_lib.h"
	#include "gpio_task.h"
	#include "delay_task.h"
	//////////////////////////////////////////////////////////////////////////////////////

	//===SOTA的配置
	#define SOTA_CTR_PORT								GPIOE
	#define SOTA_CTR_BIT								LL_GPIO_PIN_11
	#define SOTA_CTR_STATE								GPIO_GET_STATE(SOTA_CTR_PORT,SOTA_CTR_BIT)
	#define SOTA_CTR_WRITE								GPIO_SET_WRITE(SOTA_CTR_PORT,SOTA_CTR_BIT)
	#define SOTA_CTR_READ								GPIO_SET_READ( SOTA_CTR_PORT,SOTA_CTR_BIT)
	#define SOTA_CTR_OUT_0								GPIO_OUT_0(    SOTA_CTR_PORT,SOTA_CTR_BIT)
	#define SOTA_CTR_OUT_1								GPIO_OUT_1(    SOTA_CTR_PORT,SOTA_CTR_BIT)
	#define SOTA_CTR_OUT_C								GPIO_OUT_C(    SOTA_CTR_PORT,SOTA_CTR_BIT)

	//===EOTA的配置
	#define EOTA_CTR_PORT								GPIOE
	#define EOTA_CTR_BIT								LL_GPIO_PIN_12
	#define EOTA_CTR_STATE								GPIO_GET_STATE(EOTA_CTR_PORT,EOTA_CTR_BIT)
	#define EOTA_CTR_WRITE								GPIO_SET_WRITE(EOTA_CTR_PORT,EOTA_CTR_BIT)
	#define EOTA_CTR_READ								GPIO_SET_READ( EOTA_CTR_PORT,EOTA_CTR_BIT)
	#define EOTA_CTR_OUT_0								GPIO_OUT_0(    EOTA_CTR_PORT,EOTA_CTR_BIT)
	#define EOTA_CTR_OUT_1								GPIO_OUT_1(    EOTA_CTR_PORT,EOTA_CTR_BIT)
	#define EOTA_CTR_OUT_C								GPIO_OUT_C(    EOTA_CTR_PORT,EOTA_CTR_BIT)

	//===BINA的配置
	#define BINA_CTR_PORT								GPIOE
	#define BINA_CTR_BIT								LL_GPIO_PIN_13
	#define BINA_CTR_STATE								GPIO_GET_STATE(BINA_CTR_PORT,BINA_CTR_BIT)
	#define BINA_CTR_WRITE								GPIO_SET_WRITE(BINA_CTR_PORT,BINA_CTR_BIT)
	#define BINA_CTR_READ								GPIO_SET_READ( BINA_CTR_PORT,BINA_CTR_BIT)
	#define BINA_CTR_OUT_0								GPIO_OUT_0(    BINA_CTR_PORT,BINA_CTR_BIT)
	#define BINA_CTR_OUT_1								GPIO_OUT_1(    BINA_CTR_PORT,BINA_CTR_BIT)
	#define BINA_CTR_OUT_C								GPIO_OUT_C(    BINA_CTR_PORT,BINA_CTR_BIT)

	//===DECA的配置
	#define DECA_PASS_CTR_PORT							GPIOE
	#define DECA_PASS_CTR_BIT							LL_GPIO_PIN_15
	#define DECA_PASS_CTR_STATE							GPIO_GET_STATE(DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_WRITE							GPIO_SET_WRITE(DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_READ							GPIO_SET_READ( DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_OUT_0							GPIO_OUT_0(    DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_OUT_1							GPIO_OUT_1(    DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_OUT_C							GPIO_OUT_C(    DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)

	//===SOTB的配置
	#define SOTB_CTR_PORT								GPIOE
	#define SOTB_CTR_BIT								LL_GPIO_PIN_2
	#define SOTB_CTR_STATE								GPIO_GET_STATE(SOTB_CTR_PORT,SOTB_CTR_BIT)
	#define SOTB_CTR_WRITE								GPIO_SET_WRITE(SOTB_CTR_PORT,SOTB_CTR_BIT)
	#define SOTB_CTR_READ								GPIO_SET_READ( SOTB_CTR_PORT,SOTB_CTR_BIT)
	#define SOTB_CTR_OUT_0								GPIO_OUT_0(    SOTB_CTR_PORT,SOTB_CTR_BIT)
	#define SOTB_CTR_OUT_1								GPIO_OUT_1(    SOTB_CTR_PORT,SOTB_CTR_BIT)
	#define SOTB_CTR_OUT_C								GPIO_OUT_C(    SOTB_CTR_PORT,SOTB_CTR_BIT)

	//===EOTB的配置
	#define EOTB_CTR_PORT								GPIOE
	#define EOTB_CTR_BIT								LL_GPIO_PIN_3
	#define EOTB_CTR_STATE								GPIO_GET_STATE(EOTB_CTR_PORT,EOTB_CTR_BIT)
	#define EOTB_CTR_WRITE								GPIO_SET_WRITE(EOTB_CTR_PORT,EOTB_CTR_BIT)
	#define EOTB_CTR_READ								GPIO_SET_READ( EOTB_CTR_PORT,EOTB_CTR_BIT)
	#define EOTB_CTR_OUT_0								GPIO_OUT_0(    EOTB_CTR_PORT,EOTB_CTR_BIT)
	#define EOTB_CTR_OUT_1								GPIO_OUT_1(    EOTB_CTR_PORT,EOTB_CTR_BIT)
	#define EOTB_CTR_OUT_C								GPIO_OUT_C(    EOTB_CTR_PORT,EOTB_CTR_BIT)

	//===BINB的配置
	#define BINB_CTR_PORT								GPIOE
	#define BINB_CTR_BIT								LL_GPIO_PIN_4
	#define BINB_CTR_STATE								GPIO_GET_STATE(BINB_CTR_PORT,BINB_CTR_BIT)
	#define BINB_CTR_WRITE								GPIO_SET_WRITE(BINB_CTR_PORT,BINB_CTR_BIT)
	#define BINB_CTR_READ								GPIO_SET_READ( BINB_CTR_PORT,BINB_CTR_BIT)
	#define BINB_CTR_OUT_0								GPIO_OUT_0(    BINB_CTR_PORT,BINB_CTR_BIT)
	#define BINB_CTR_OUT_1								GPIO_OUT_1(    BINB_CTR_PORT,BINB_CTR_BIT)
	#define BINB_CTR_OUT_C								GPIO_OUT_C(    BINB_CTR_PORT,BINB_CTR_BIT)

	//===DECB的配置
	#define DECB_PASS_CTR_PORT							GPIOE
	#define DECB_PASS_CTR_BIT							LL_GPIO_PIN_6
	#define DECB_PASS_CTR_STATE							GPIO_GET_STATE(DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_WRITE							GPIO_SET_WRITE(DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_READ							GPIO_SET_READ( DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_OUT_0							GPIO_OUT_0(    DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_OUT_1							GPIO_OUT_1(    DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_OUT_C							GPIO_OUT_C(    DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)

	//===SOTC的配置
	#define SOTC_CTR_PORT								GPIOD
	#define SOTC_CTR_BIT								LL_GPIO_PIN_3
	#define SOTC_CTR_STATE								GPIO_GET_STATE(SOTC_CTR_PORT,SOTC_CTR_BIT)
	#define SOTC_CTR_WRITE								GPIO_SET_WRITE(SOTC_CTR_PORT,SOTC_CTR_BIT)
	#define SOTC_CTR_READ								GPIO_SET_READ( SOTC_CTR_PORT,SOTC_CTR_BIT)
	#define SOTC_CTR_OUT_0								GPIO_OUT_0(    SOTC_CTR_PORT,SOTC_CTR_BIT)
	#define SOTC_CTR_OUT_1								GPIO_OUT_1(    SOTC_CTR_PORT,SOTC_CTR_BIT)
	#define SOTC_CTR_OUT_C								GPIO_OUT_C(    SOTC_CTR_PORT,SOTC_CTR_BIT)

	//===EOTC的配置
	#define EOTC_CTR_PORT								GPIOD
	#define EOTC_CTR_BIT								LL_GPIO_PIN_2
	#define EOTC_CTR_STATE								GPIO_GET_STATE(EOTC_CTR_PORT,EOTC_CTR_BIT)
	#define EOTC_CTR_WRITE								GPIO_SET_WRITE(EOTC_CTR_PORT,EOTC_CTR_BIT)
	#define EOTC_CTR_READ								GPIO_SET_READ( EOTC_CTR_PORT,EOTC_CTR_BIT)
	#define EOTC_CTR_OUT_0								GPIO_OUT_0(    EOTC_CTR_PORT,EOTC_CTR_BIT)
	#define EOTC_CTR_OUT_1								GPIO_OUT_1(    EOTC_CTR_PORT,EOTC_CTR_BIT)
	#define EOTC_CTR_OUT_C								GPIO_OUT_C(    EOTC_CTR_PORT,EOTC_CTR_BIT)

	//===BINC的配置
	#define BINC_CTR_PORT								GPIOD
	#define BINC_CTR_BIT								LL_GPIO_PIN_1
	#define BINC_CTR_STATE								GPIO_GET_STATE(BINC_CTR_PORT,BINC_CTR_BIT)
	#define BINC_CTR_WRITE								GPIO_SET_WRITE(BINC_CTR_PORT,BINC_CTR_BIT)
	#define BINC_CTR_READ								GPIO_SET_READ( BINC_CTR_PORT,BINC_CTR_BIT)
	#define BINC_CTR_OUT_0								GPIO_OUT_0(    BINC_CTR_PORT,BINC_CTR_BIT)
	#define BINC_CTR_OUT_1								GPIO_OUT_1(    BINC_CTR_PORT,BINC_CTR_BIT)
	#define BINC_CTR_OUT_C								GPIO_OUT_C(    BINC_CTR_PORT,BINC_CTR_BIT)

	//===DECC的配置
	#define DECC_PASS_CTR_PORT							GPIOC
	#define DECC_PASS_CTR_BIT							LL_GPIO_PIN_12
	#define DECC_PASS_CTR_STATE							GPIO_GET_STATE(DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_WRITE							GPIO_SET_WRITE(DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_READ							GPIO_SET_READ( DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_OUT_0							GPIO_OUT_0(    DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_OUT_1							GPIO_OUT_1(    DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_OUT_C							GPIO_OUT_C(    DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)

	//===SOTD的配置
	#define SOTD_CTR_PORT								GPIOD
	#define SOTD_CTR_BIT								LL_GPIO_PIN_11
	#define SOTD_CTR_STATE								GPIO_GET_STATE(SOTD_CTR_PORT,SOTD_CTR_BIT)
	#define SOTD_CTR_WRITE								GPIO_SET_WRITE(SOTD_CTR_PORT,SOTD_CTR_BIT)
	#define SOTD_CTR_READ								GPIO_SET_READ( SOTD_CTR_PORT,SOTD_CTR_BIT)
	#define SOTD_CTR_OUT_0								GPIO_OUT_0(    SOTD_CTR_PORT,SOTD_CTR_BIT)
	#define SOTD_CTR_OUT_1								GPIO_OUT_1(    SOTD_CTR_PORT,SOTD_CTR_BIT)
	#define SOTD_CTR_OUT_C								GPIO_OUT_C(    SOTD_CTR_PORT,SOTD_CTR_BIT)

	//===EOTD的配置
	#define EOTD_CTR_PORT								GPIOD
	#define EOTD_CTR_BIT								LL_GPIO_PIN_10
	#define EOTD_CTR_STATE								GPIO_GET_STATE(EOTD_CTR_PORT,EOTD_CTR_BIT)
	#define EOTD_CTR_WRITE								GPIO_SET_WRITE(EOTD_CTR_PORT,EOTD_CTR_BIT)
	#define EOTD_CTR_READ								GPIO_SET_READ( EOTD_CTR_PORT,EOTD_CTR_BIT)
	#define EOTD_CTR_OUT_0								GPIO_OUT_0(    EOTD_CTR_PORT,EOTD_CTR_BIT)
	#define EOTD_CTR_OUT_1								GPIO_OUT_1(    EOTD_CTR_PORT,EOTD_CTR_BIT)
	#define EOTD_CTR_OUT_C								GPIO_OUT_C(    EOTD_CTR_PORT,EOTD_CTR_BIT)

	//===BIND的配置
	#define BIND_CTR_PORT								GPIOD
	#define BIND_CTR_BIT								LL_GPIO_PIN_9
	#define BIND_CTR_STATE								GPIO_GET_STATE(BIND_CTR_PORT,BIND_CTR_BIT)
	#define BIND_CTR_WRITE								GPIO_SET_WRITE(BIND_CTR_PORT,BIND_CTR_BIT)
	#define BIND_CTR_READ								GPIO_SET_READ( BIND_CTR_PORT,BIND_CTR_BIT)
	#define BIND_CTR_OUT_0								GPIO_OUT_0(    BIND_CTR_PORT,BIND_CTR_BIT)
	#define BIND_CTR_OUT_1								GPIO_OUT_1(    BIND_CTR_PORT,BIND_CTR_BIT)
	#define BIND_CTR_OUT_C								GPIO_OUT_C(    BIND_CTR_PORT,BINC_CTR_BIT)

	//===DECD成功的配置
	#define DECD_PASS_CTR_PORT							GPIOB
	#define DECD_PASS_CTR_BIT							LL_GPIO_PIN_15
	#define DECD_PASS_CTR_STATE							GPIO_GET_STATE(DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_WRITE							GPIO_SET_WRITE(DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_READ							GPIO_SET_READ( DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_OUT_0							GPIO_OUT_0(    DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_OUT_1							GPIO_OUT_1(    DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_OUT_C							GPIO_OUT_C(    DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)

	//===函数调用
	void Key_Init();
	UINT8_T Key_GetSOT(void);
	UINT8_T Key_ScanSOT(void);
	void Key_EOTSTART(void);
	void Key_EOTSTOP(void);
	void Key_BINAPass(UINT8_T isPass);
	void Key_BINBPass(UINT8_T isPass);
	void Key_BINCPass(UINT8_T isPass);
	void Key_BINDPass(UINT8_T isPass);
	//////////////////////////////////////////////////////////////////////////////////////
	#ifdef __cplusplus
}
#endif
//////////////////////////////////////////////////////////////////////////////////////
#endif /*KEY_CFG_H_ */